language: generic

env:
  global:
    - CXXFLAGS="-Wall -Werror"
    - CFLAGS="-Wall -Werror"
    - LD_LIBRARY_PATH='/usr/local/lib'
    - PKG_CONFIG_PATH='/usr/local/lib/pkgconfig'

matrix:
  include:
    - os: linux
      sudo: required
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: 'deb [arch=amd64] http://xmi-apt.tomschoonjans.eu/ubuntu bionic stable'
              key_url: 'http://xmi-apt.tomschoonjans.eu/xmi.packages.key'
          packages:
            - libgsl0-dev
            - libxrl11-dev
            - libhdf5-serial-dev
            - hdf5-tools
            - gcc
            - python3-all-dev
            - python3-numpy
      env: PYTHON='/usr/bin/python3'
    - os: linux
      sudo: required
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: 'deb [arch=amd64] http://xmi-apt.tomschoonjans.eu/ubuntu bionic stable'
              key_url: 'http://xmi-apt.tomschoonjans.eu/xmi.packages.key'
          packages:
            - libgsl0-dev
            - libeasyrng-dev
            - libxrl11-dev
            - libhdf5-serial-dev
            - hdf5-tools
            - gcc
            - python3-all-dev
            - python3-numpy
      env: PYTHON='/usr/bin/python3'
    - os: osx
      sudo: required
      env: CC='/usr/local/opt/llvm/bin/clang' HOMEBREW_ARGS='llvm' EXTRA_LIBS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' PYTHON='/usr/local/opt/python@3.8/bin/python3'
    - os: osx
      sudo: required
      env: CC='/usr/local/bin/gcc-9' HOMEBREW_ARGS='gcc@9' PYTHON='/usr/local/opt/python@3.8/bin/python3'
    - os: osx
      sudo: required
      env: CC='/usr/local/opt/llvm/bin/clang' HOMEBREW_ARGS='llvm tschoonj/tap/easyrng' EXTRA_LIBS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' PYTHON='/usr/local/opt/python@3.8/bin/python3'
    - os: osx
      sudo: required
      env: CC='/usr/local/bin/gcc-9' HOMEBREW_ARGS='gcc@9 tschoonj/tap/easyrng' PYTHON='/usr/local/opt/python@3.8/bin/python3'

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ] ; then
      rm -rf $(brew --prefix)/lib/python*
      rm -rf $(brew --prefix)/bin/f2py*
      brew cask uninstall --force oclint
      brew uninstall --force --ignore-dependencies $(brew list) || exit 1
      brew update || exit 1
      brew cleanup -s || exit 1
      rm -rf $(brew --cache) || exit 1
      brew install hdf5 git autoconf automake libtool curl wget pkg-config gsl python@3.8 numpy || exit 1
      brew install $HOMEBREW_ARGS tschoonj/tap/xraylib || exit 1
      /usr/local/opt/python@3.8/bin/pip3
      brew cleanup -s || exit 1
      rm -rf $(brew --cache) || exit 1
    else
      sudo pip install Cython || exit 1
      export PATH=/usr/local/bin:$PATH
    fi

script:
  - autoreconf -fi || exit 1
  - export LIBS="$LIBS $EXTRA_LIBS"
  - ./configure --disable-python || (cat config.log && exit 1)
  - make || exit 1
  - make check || exit 1
  - make distclean || exit 1
  - ./configure --enable-python PYTHON=${XRL_PYTHON3} || exit 1
  - make || exit 1
  - make check || exit 1
  - make distcheck || exit 1

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
      - Pieter.Tack@UGent.be
    on_success: never
    on_failure: always

branches:
  only:
    - master

