name: CI

on:
  #schedule:
  #  - cron: '0 2 * * *' # run at 2 AM UTC
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  EASYRNG_VERSION: 1.2
  XRAYLIB_VERSION: 4.1.3

jobs:

  visual-studio:
    timeout-minutes: 60
    runs-on: windows-latest
    strategy:
      matrix:
        python-version:
          # - '3.8'
          # - '3.9'
          # - '3.10'
          - '3.11'
        compiler:
          - cl
          # - clang-cl
    name: visual studio with ${{matrix.compiler}} and python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Mambaforge
        use-mamba: true
    - name: install conda dependencies
      run: |
        mamba install -q -y meson ninja numpy cython xraylib hdf5 gsl m2w64-pkg-config zlib
    - uses: ilammy/msvc-dev-cmd@v1
    - name: build and test with meson
      run: |
        Copy-Item -Path ".ci_support\gsl.pc" -Destination "$Env:CONDA_PREFIX\Library\lib\pkgconfig"
        $Env:CPPFLAGS = "-DH5_BUILT_AS_DYNAMIC_LIB=1 -D_CRT_SECURE_NO_WARNINGS=1"
        $Env:PKG_CONFIG_PATH = "$Env:CONDA_PREFIX\Library\lib\pkgconfig;$Env:CONDA_PREFIX\Library\share\pkgconfig"
        meson setup meson-build --buildtype=release -Dpython=python -Dbuild-python-bindings=true
        meson compile -C meson-build
        meson test -C meson-build
        cat meson-build\meson-logs\testlog.txt
      env:
        cc: ${{ matrix.compiler }}
        cxx: ${{ matrix.compiler }}

  msys2:
    timeout-minutes: 60
    strategy:
      matrix:
        cc:
          - clang
          - gcc
        buildsystem:
          - meson
        rng:
          - easyRNG
          - gsl
        include:
          - cc: clang
            cxx: clang++
          - cc: gcc
            cxx: g++
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >
          base-devel
          git
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-meson
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-openmp
          mingw-w64-x86_64-lld
          mingw-w64-x86_64-hdf5
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-curl
          mingw-w64-x86_64-gsl
          mingw-w64-x86_64-cython
          mingw-w64-x86_64-python3-numpy
          make
          patch
    - uses: actions/checkout@v3
    - name: Install xraylib
      run: |
        set -ex
        curl -OLs https://xraylib.tomschoonjans.eu/xraylib-${XRAYLIB_VERSION}.tar.gz
        tar xvfz xraylib-${XRAYLIB_VERSION}.tar.gz
        cd xraylib-${XRAYLIB_VERSION}
        ./configure
        make
        make install
        set +ex
      env:
        CC: gcc
        CFLAGS: " -Wno-error=deprecated-declarations "
    - name: Install easyrng
      if: matrix.rng == 'easyRNG'
      run: |
        set -ex
        curl -OLs https://github.com/tschoonj/easyRNG/releases/download/easyRNG-${EASYRNG_VERSION}/easyRNG-${EASYRNG_VERSION}.tar.gz
        tar xvfz easyRNG-${EASYRNG_VERSION}.tar.gz
        cd easyRNG-${EASYRNG_VERSION}
        ./configure
        make
        make install
        set +ex
      env:
        CC: gcc
        CXX: g++
    - name: Build and test with Meson
      run: |
        set -ex
        mkdir build-tmp
        cd build-tmp
        meson --buildtype=debugoptimized -Dpython=python3 -Dbuild-documentation=false ..
        meson compile
        meson test
        set +ex
      env:
        CC: ${{matrix.cc}}

  unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rng: [easyRNG, gsl]
        compiler: [clang, gcc]
        buildsystem: [meson]
        include:
          # Linux
          - os: ubuntu-latest
            rng: easyRNG
            compiler: clang
            cc: clang
            python: /usr/bin/python3
          - os: ubuntu-latest
            rng: easyRNG
            compiler: gcc
            cc: gcc
            python: /usr/bin/python3
          - os: ubuntu-latest
            rng: gsl
            compiler: clang
            cc: clang
            python: /usr/bin/python3
          - os: ubuntu-latest
            rng: gsl
            compiler: gcc
            cc: gcc
            python: /usr/bin/python3
          # macOS
          - os: macos-latest
            rng: easyRNG
            compiler: clang
            cc: /usr/local/opt/llvm/bin/clang
            extra: tschoonj/tap/easyrng
            python: /usr/local/bin/python3
            libs: -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib
          - os: macos-latest
            rng: easyRNG
            compiler: gcc
            cc: /usr/local/bin/gcc-12
            extra: tschoonj/tap/easyrng
            python: /usr/local/bin/python3
          - os: macos-latest
            rng: gsl
            compiler: clang
            cc: /usr/local/opt/llvm/bin/clang
            python: /usr/local/bin/python3
            libs: -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib
          - os: macos-latest
            rng: gsl
            compiler: gcc
            cc: /usr/local/bin/gcc-12
            python: /usr/local/bin/python3

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Install ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        set -ex
        sudo apt-get update
        # sudo apt-get upgrade -> takes very long!
        sudo apt-get install libomp-dev libgsl0-dev python3-pip python3-wheel python3-setuptools libhdf5-serial-dev hdf5-tools gcc python3-all-dev python3-numpy cython3
        pip3 install meson ninja
        curl -OLs https://github.com/tschoonj/easyRNG/releases/download/easyRNG-${EASYRNG_VERSION}/easyRNG-${EASYRNG_VERSION}.tar.gz
        tar xvfz easyRNG-${EASYRNG_VERSION}.tar.gz
        cd easyRNG-${EASYRNG_VERSION}
        ./configure
        make
        sudo make install
        curl -OLs https://xraylib.tomschoonjans.eu/xraylib-${XRAYLIB_VERSION}.tar.gz
        tar xvfz xraylib-${XRAYLIB_VERSION}.tar.gz
        cd xraylib-${XRAYLIB_VERSION}
        ./configure
        make
        sudo make install
        set +ex
    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        set -ex
        rm -f /usr/local/bin/2to3
        brew uninstall -f bazel bazelisk
        brew update
        brew upgrade || true
        brew install hdf5 git curl wget pkg-config gsl
        brew install ${{ matrix.extra }} tschoonj/tap/xraylib
        pip3 install Cython numpy meson ninja
        set +ex
      env:
        HOMEBREW_CURL_RETRIES: 5
    - name: Primary build and test with meson
      run: |
        set -ex
        export PATH=${HOME}/.local/bin:${PATH}
        unset PKG_CONFIG_LIBDIR
        mkdir build
        cd build
        meson setup --buildtype=debugoptimized -Dbuild-python-bindings=false -Dbuild-documentation=false ..
        meson compile
        meson test || (cat meson-logs/testlog.txt && exit 1)
        meson compile --clean
        rm -rf *
        meson --buildtype=debugoptimized -Dpython=${{matrix.python}} -Dbuild-documentation=false .. || (cat meson-logs/meson-log.txt && exit 1)
        meson compile
        meson dist
        set +ex
      env:
        CC: ${{matrix.cc}}
        LDFLAGS: ${{matrix.libs}}
        CPPFLAGS: -I/usr/local/opt/hdf5/include

